CREATE TABLE `project_material_checklists` (
	`id` int AUTO_INCREMENT NOT NULL,
	`createdByUserId` int NOT NULL,
	`createdByName` varchar(255),
	`projectName` varchar(255) NOT NULL,
	`clientName` varchar(255),
	`projectLocation` text,
	`supervisorUserId` int,
	`supervisorName` varchar(255),
	`status` varchar(64) NOT NULL DEFAULT 'draft',
	`boxedItems` json,
	`deliveryItems` json,
	`projectSpecificItems` json,
	`warehouseCheckoffs` json,
	`auditTrail` json,
	`attachments` json,
	`materialsLoadedPhotos` json,
	`materialsDeliveredPhotos` json,
	`materialsLoaded` boolean NOT NULL DEFAULT false,
	`materialsDelivered` boolean NOT NULL DEFAULT false,
	`companyId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `project_material_checklists_id` PRIMARY KEY(`id`)
);
