CREATE TABLE `aquaclean_receipts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`companyId` int,
	`projectId` int,
	`submitterName` varchar(255),
	`vendorName` varchar(255),
	`vendorLocation` text,
	`purchaseDate` varchar(10),
	`subtotal` decimal(10,2),
	`tax` decimal(10,2),
	`total` decimal(10,2),
	`imageUrl` text,
	`lineItems` json,
	`workOrderNumber` varchar(64),
	`jobName` varchar(255),
	`poNumber` varchar(64),
	`materialCategory` varchar(64) DEFAULT 'Miscellaneous',
	`expenseType` enum('JOB','OVERHEAD') DEFAULT 'JOB',
	`overheadCategory` varchar(128),
	`notes` text,
	`fileName` varchar(255),
	`archived` boolean NOT NULL DEFAULT false,
	`archivedAt` timestamp,
	`archivedBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `aquaclean_receipts_id` PRIMARY KEY(`id`)
);
